name: Dart CI

on:
  push:
    branches: 
      - main
      : 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Set up Node.js environment
      with:
        node-version: '12'  # Use Node.js version 12

    - name: Install dependencies
      run: npm install  # Install project dependencies using npm

    - name: Set up Java
      uses: actions/setup-java@v1  # Set up Java environment
      with:
        java-version: '17.x'  # Use Java version 17.x

    - name: Set up Flutter
      uses: subosito/flutter-action@v2  # Set up Flutter environment
      with:
        channel: 'stable'  # Use the stable Flutter channel
        architecture: x64  # Use x64 architecture

    - name: Install Flutter dependencies
      run: flutter pub get  # Install Flutter project dependencies

    - name: Build Android APK
      run: |
        flutter build apk # Build the release version of the APK
        mv ./build/app/outputs/apk/release/* ./web  # Move the APK to web directory

    - name: Deploy APK Artifact
      uses: actions/upload-artifact@v3  # Upload APK artifact to GitHub
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk  # Path to the APK file

    - name: Release APK
      uses: ncipollo/release-action@v1.5.0  # Release APK on GitHub
      with:
        artifacts: "build/app/outputs/flutter-apk/*.apk"  # APK artifact
        token: ${{ secrets.GIT_TOKEN }}  # Use GitHub secret to fetch GitHub Token
        commit: main  # Target commit
        tag: v1.0.${{ github.run_number }}  # Tag with version number
